### ISSUE TITLE
"android.py install" crashes while installing Android SDK

### ISSUE THREAD

**Issue by ghost** [renpy/python-for-android#1]
`android.py install` consistently crashes while installing the Android SDK, producing output that ends like this:

```
Error: Ignoring unknown package filter 'android-8'
Error: Ignoring unknown package filter 'android-15'
Error: Ignoring unknown package filter 'extra-google-play_licensing'
Error: Ignoring unknown package filter 'extra-google-play_apk_expansion'
Installing Archives:
  Preparing to install archives
  Downloading Android SDK Platform-tools, revision 19.0.1
  Installing Android SDK Platform-tools, revision 19.0.1
  Stopping ADB server failed (code -1).
    Installed Android SDK Platform-tools, revision 19.0.199%)
    Stopping ADB server succeeded.
    Starting ADB server succeeded.
  Done. 1 package installed.

I'm updating the library packages.

Traceback (most recent call last):
  File "android.py", line 66, in <module>
    main()
  File "android.py", line 40, in main
    install_sdk.install_sdk(iface)
  File "buildlib/install_sdk.py", line 225, in install_sdk
    get_packages(interface)
  File "buildlib/install_sdk.py", line 160, in get_packages
    with open("android-sdk/extras/google/play_apk_expansion/downloader_library/project.properties", "r") as f:
IOError: [Errno 2] No such file or directory: 'android-sdk/extras/google/play_apk_expansion/downloader_library/project.properties'
```

This appears to be due to the current Android SDK having a different file structure than the version PGS4A was written to handle.

**Comment by renpytom** [comment]
psg4a is obsolete. please see https://github.com/renpytom/rapt-pygame-example for a supported solution.
